var road_trips = [
    {
        "trip_name": "Chicago-San Francisco Trip",
        "start_location": "Chicago, IL",  
        "end_location": "San Francisco, CA",
        "start_date": "June 1, 2015",
        "end_date": "June 20, 2015",
        "stops": ["St. Louis, MO", "Kansas City, KS", "Denver, CO", "Salt Lake City, UT", "South Lake Tahoe, CA"],
        "duration": "20 days",
        "total_distance": "2424 miles",
        "num_companions": "3 companions",
        "notes": "This is a trip I have been planning for a while. I will be stopping in various cities and would love to also see some great nature along the way, especially near the Rockies. I have an SUV so there is plenty of space for stuff! I'll be driving back to Chicago without stopping for sightseeing, and you are welcome to drive back with me.",
        "are_dates_flexible": true,
    },

    {
        "trip_name": "Cross-country Adventure",
        "start_location": "Boston, MA",  
        "end_location": "San Diego, CA",
        "start_date": "June 12, 2015",
        "end_date": "July 12, 2015",
        "stops": ["New York City, NY", "Philadelphia, PA", "Chicago, IL", "Keystone, SD", "Cody, WY", "Salt Lake City, UT", "Las Vegas, NV", "Los Angeles, CA"],
        "duration": "1 month",
        "total_distance": "3654 miles",  
        "num_companions": "2 companions",      
        "notes": "Epic trip across the US, stopping at many must-see places. I am relocating to San Diego, so you would have to fly back, but tickets are pretty cheap if you buy this far in advance.",
        "are_dates_flexible": false,
    },

    {
        "trip_name": "West Coast Road Trip",
        "start_location": "Los Angeles, CA",  
        "end_location": "Vancouver, BC",
        "start_date": "June 5, 2015",
        "end_date": "June 30, 2015",
        "stops": ["Santa Barbara, CA", "Pismo Beach, CA", "Big Sur, CA", "San Francisco, CA", "Leggett, CA", "Coos Bay, OR", "Portland, OR", "Seattle, WA"],
        "duration": "25 days",
        "total_distance": "1479 miles",  
        "num_companions": "1 companion",      
        "notes": "Coastside drive up Highway 1 in California, and US 101 north of that. We'll stop in the cities and by random beaches we find. Also, drive-thru redwood trees and the Pacific Northwest!",
        "are_dates_flexible": true,
    },

    {
        "trip_name": "New York-Montreal Trip",
        "start_location": "New York City, NY",  
        "end_location": "Montreal, QC",
        "start_date": "June 2, 2015",
        "end_date": "June 12, 2015",
        "stops": ["Boston, MA", "Portsmouth, NH", "Burlington, VT"],
        "duration": "10 days",
        "total_distance": "606 miles",        
        "num_companions": "2 companions",
        "notes": "Trip to Montreal through the historic Boston and the New England countryside",
        "are_dates_flexible": true,
    },    

    {
        "trip_name": "Boston-Charleston Trip",
        "start_location": "Boston, MA",  
        "end_location": "Charleston, SC",
        "start_date": "June 1, 2015",
        "end_date": "June 21, 2015",
        "stops": ["New York City, NY", "Philadelphia, PA", "Washington, DC", "Richmond, VA", "Virginia Beach, VA"],
        "duration": "21 days",
        "total_distance": "1121 miles",        
        "num_companions": "1 companion",
        "notes": "",
        "are_dates_flexible": true,
    },        
]